[package]
name = "ballistic-defence"
version = "0.1.0"
authors = ["ducaale <sharaf.13@hotmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.1"
cgmath = { version = "0.17", features = ["mint"] }
rand = "0.6"